image: docker:stable

services:
  - docker:dind

stages:
  - build
  - test

before_script:
  - apk add --no-cache py-pip python-dev libffi-dev openssl-dev gcc libc-dev make
  - pip install --no-cache-dir docker-compose
  - export REACT_APP_USERS_SERVICE_URL=http://127.0.0.1

compile:
  stage: build
  script:
    - docker-compose up --build -d


test:
  stage: test
  script:
    - docker-compose exec users python manage.py test

after_script:
  - docker-compose down